name: Run module tests
on:
  pull_request: 
    branches:
      - '*'
    paths:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Terratest
    
    defaults:
      run:
        working-directory: ./tests
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Authenticate with Azure
      uses: azure/login@v2
      with:
        creds: '{"clientId": "${{ secrets.ARM_CLIENT_ID }}", "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}", "tenantId": "${{ secrets.ARM_TENANT_ID }}", "subscriptionId": "${{ vars.ARM_SUBSCRIPTION_ID }}"}'
    
    - name: install terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ vars.TERRAFORM_VERSION }}

    - name: Run tests
      id: tests
      run: |
        go test -v ./...
      