name: Run module tests
on:
  pull_request: 
    branches:
      - '*'
    paths:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run tests on docker image
    
    defaults:
      run:
        working-directory: ./tests
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run tests
      id: tests
      run: |
        go test -v ./...
      